jobs:

# jobs for the box demo pipelines for PROD environment

################################

# BOX JOBS
# PROD deployment
  - name: box-prod-triton
    type: ecsDeploy
    steps:
      - GET: box-test-triton
        trigger: false
      - GET: box-p-params
      - GET: box-p-scaler
      - GET: env-prod-triton
      - GET: box-p-kick

# # DR deployment
#   - name: box-prod-triton
#     type: ecsDeploy
#     steps:
#       - GET: box-test-triton
#         trigger: false
#       - GET: box-p-params
#       - GET: box-p-scaler
#       - GET: env-prod-triton
#       - GET: box-p-kick
