triggers:
  # - name: trigger-prod-deploy-dv
  #   type: trigger
  #   source:
  #     message: 'testing trigger in test'
  #
  - name: trigger-prod-deploy-box
    type: trigger
    source:
      message: "deploy to prod"
