jobs:

# jobs for the box demo pipelines for PROD environment

####3: Add prod for BOX
# PROD deployment - Amazon ECS
  - name: box-prod-ecs
    type: ecsDeploy
    steps:
      - IN: box-test-aws-ecs
        trigger: false
      - IN: box-p-ecs-scaler
      - IN: box-p-ecs-params
      - IN: env-prod-ecs
      - TASK: managed

####3: End Add prod for BOX

####4: Add DR for BOX

#DR deployment - Google Container Engine
  - name: box-dr-gke
    type: gkeDeploy
    steps:
      - IN: box-test-aws-ecs
        trigger: false
      - IN: box-p-gke-scaler
      - IN: box-p-gke-params
      - IN: dr-demo-gke
      - TASK: managed

#####4: Add DR for BOX
  