triggers:
  - name: trigger-prod-deploy-box
    type: trigger
    version:
      message: "deploy to prod"

  - name: trigger-prod-deploy-dv
    type: trigger
    version:
      message: 'testing trigger in test'
