jobs:

# jobs for the box demo pipelines for PROD environment

################################

# 5) add deploy config for PROD

# BOX JOBS
# PROD deployment - Joyent Triton
  - name: box-prod-triton
    type: tripubDeploy
    steps:
      - GET: box-test-triton
        trigger: false
      - GET: box-p-params
      - GET: box-p-scaler
      - GET: env-prod-triton
      - GET: box-p-kick
      - GET: trigger-prod-deploy-box

# PROD deployment - Amazon ECS
  - name: box-prod-ecs
    type: ecsDeploy
    steps:
      - GET: box-test-ecs
        trigger: false
      - GET: box-p-scaler
      - GET: box-d-params
      - GET: env-prod-ecs
      - GET: box-p-kick
      - GET: trigger-prod-deploy-box
