jobs:

# jobs for the box demo pipelines for PROD environment

################################

# 5) add deploy config for PROD
# BOX JOBS
# PROD deployment
  - name: box-prod-triton
    type: tripubDeploy
    steps:
      - GET: box-test-triton
        trigger: false
      - GET: box-p-params
      - GET: box-p-scaler
      - GET: env-prod-triton
      - GET: box-p-kick

################################

# 7) deploy to DR
# # DR deployment
#   - name: box-prod-triton
#     type: ecsDeploy
#     steps:
#       - GET: box-test-triton
#         trigger: false
#       - GET: box-d-params
#       - GET: box-p-scaler
#       - GET: env-prod-triton
#       - GET: box-p-kick
